#!/usr/bin/env python3
import argparse
import os

import torch
import torchmetrics

import npfl138
npfl138.require_version("2526.7")
from npfl138.datasets.morpho_dataset import MorphoDataset
from npfl138.datasets.morpho_analyzer import MorphoAnalyzer

# TODO: Define reasonable defaults and optionally more parameters.
# Also, you can set the number of threads to 0 to use all your CPU cores.
parser = argparse.ArgumentParser()
parser.add_argument("--batch_size", default=64, type=int, help="Batch size.")
parser.add_argument("--cle_dim", default=32, type=int, help="CLE embedding dimension.")
parser.add_argument("--epochs", default=10, type=int, help="Number of epochs.")
parser.add_argument("--max_sentences", default=None, type=int, help="Maximum number of sentences to load.")
parser.add_argument("--recodex", default=False, action="store_true", help="Evaluation in ReCodEx.")
parser.add_argument("--rnn", default="LSTM", choices=["LSTM", "GRU"], help="RNN layer type.")
parser.add_argument("--rnn_dim", default=128, type=int, help="RNN layer dimension.")
parser.add_argument("--seed", default=42, type=int, help="Random seed.")
parser.add_argument("--threads", default=1, type=int, help="Maximum number of threads to use.")
parser.add_argument("--we_dim", default=64, type=int, help="Word embedding dimension.")
parser.add_argument("--word_masking", default=0.1, type=float, help="Mask words with the given probability.")

class Dataset(npfl138.TransformedDataset):
    def transform(self, example):
        word_ids = torch.tensor(self.dataset.words.string_vocab.indices(example["words"]))
        tag_ids = torch.tensor(self.dataset.tags.string_vocab.indices(example["tags"]))
        return word_ids, example["words"], tag_ids

    def collate(self, batch):
        # Construct a single batch, where `batch` is a list of examples
        # generated by `transform`.
        word_ids, words, tag_ids = zip(*batch)
        word_ids = torch.nn.utils.rnn.pad_sequence(word_ids, batch_first=True)
        # - `unique_words` with shape `[num_unique_words, max_word_length]` containing
        #   each unique word as a sequence of character ids,
        # - `words_indices` with shape `[num_sentences, max_sentence_length]`
        #   containing for every word its index in `unique_words`.
        unique_words, words_indices = self.dataset.cle_batch(words)
        tag_ids = torch.nn.utils.rnn.pad_sequence(tag_ids, batch_first=True)
        return (word_ids, unique_words, words_indices), tag_ids


class Model(npfl138.TrainableModule):
    class MaskElements(torch.nn.Module):
        """A layer randomly masking elements with a given value."""
        def __init__(self, mask_probability, mask_value):
            super().__init__()
            self._mask_probability = mask_probability
            self._mask_value = mask_value

        def forward(self, inputs: torch.Tensor) -> torch.Tensor:
            # Only mask during training and when the mask probability is non-zero.
            if self.training and self._mask_probability:
                mask = torch.rand_like(inputs, dtype=torch.float32)
                inputs = torch.where(mask < self._mask_probability, self._mask_value, inputs)
            return inputs
        
    def __init__(self, args: argparse.Namespace, train: MorphoDataset.Dataset) -> None:
        super().__init__()

        # Create all needed layers.
        self._word_masking = self.MaskElements(args.word_masking, MorphoDataset.UNK)
        self._char_embedding = torch.nn.Embedding(num_embeddings=len(train.words.char_vocab), embedding_dim=args.cle_dim)
        self._char_rnn = torch.nn.GRU(input_size=args.cle_dim, hidden_size=args.cle_dim, bidirectional=True)
        self._word_embedding = torch.nn.Embedding(num_embeddings=len(train.words.string_vocab), embedding_dim=args.we_dim)

        if args.rnn == "LSTM":
            self._word_rnn = torch.nn.LSTM(input_size=args.we_dim+2*args.cle_dim, hidden_size=args.rnn_dim, bidirectional=True)
        else:
            self._word_rnn = torch.nn.GRU(input_size=args.we_dim+2*args.cle_dim, hidden_size=args.rnn_dim, bidirectional=True)

        self._output_layer = torch.nn.LazyLinear(out_features=len(train.tags.string_vocab))

    def forward(self, word_ids: torch.Tensor, unique_words: torch.Tensor, word_indices: torch.Tensor) -> torch.Tensor:
        hidden = self._word_masking(word_ids)
        hidden = self._word_embedding(hidden)
        # Embed the `unique_words` using the character embedding layer.
        cle = self._char_embedding(unique_words)

        # Pass the character embeddings through the character-level RNN.
        lengths = (unique_words != MorphoDataset.PAD).sum(dim=1).cpu()
        packed = torch.nn.utils.rnn.pack_padded_sequence(cle, lengths=lengths, batch_first=True, enforce_sorted=False)
        # Pass the `PackedSequence` through the character RNN, obtaining fixed-size
        # representation of every unique word in the batch. Then, concatenate the states
        # of the forward and backward directions (in this order).
        _, cle = self._char_rnn(packed)
        cle = torch.cat([cle[-2], cle[-1]], dim=1)

        # With `cle` being the character-level embeddings of the unique words
        # of shape `[num_unique_words, 2 * cle_dim]`, create the representation of the
        # (not necessarily unique) sentence words by indexing the character-level
        # embeddings with the `word_indices`. The result should have a shape
        # `[batch_size, max_sentence_length, 2 * cle_dim]`.
        cle = torch.nn.functional.embedding(word_indices, cle)

        # Concatenate the word embeddings with the character-level embeddings (in this order).
        hidden = torch.cat([hidden, cle], dim=2)

        # Pass the packed embeddings through the RNN, choosing the appropriate output.
        lengths = (word_ids != MorphoDataset.PAD).sum(dim=1).cpu()
        packed = torch.nn.utils.rnn.pack_padded_sequence(hidden, lengths=lengths, batch_first=True, enforce_sorted=False)
        packed, _ = self._word_rnn(packed)

        # Unpack the RNN output using the Then sum the outputs of forward and backward directions.
        hidden, _ = torch.nn.utils.rnn.pad_packed_sequence(packed, batch_first=True)
        hidden = torch.cat([
            hidden[:, :, :self._word_rnn.hidden_size],
            hidden[:, :, self._word_rnn.hidden_size:],
        ], dim=2)

        # Pass the RNN output through the output layer. Such an output has a shape
        # `[batch_size, sequence_length, num_tags]`, but the loss and the metric expect
        # the `num_tags` dimension to be in front (`[batch_size, num_tags, sequence_length]`),
        # so you need to reorder the dimensions.
        hidden = self._output_layer(hidden).permute(0, 2, 1)
        return hidden
        
def main(args: argparse.Namespace) -> None:
    npfl138.startup(args.seed, args.threads)
    npfl138.global_keras_initializers()

    logdir = npfl138.format_logdir("logs/{file-}{timestamp}{-config}", **vars(args))

    # Load the data. Using analyses is only optional.
    morpho = MorphoDataset("czech_pdt")
    analyses = MorphoAnalyzer("czech_pdt_analyses")

    # Prepare the data for training.
    train = Dataset(morpho.train).dataloader(batch_size=args.batch_size, shuffle=True)
    dev = Dataset(morpho.dev).dataloader(batch_size=args.batch_size)
    test = Dataset(morpho.test).dataloader(batch_size=args.batch_size)

    # Create the model and train.
    model = Model(args, morpho.train)

    model.configure(
        optimizer=torch.optim.Adam(model.parameters()),
        loss=torch.nn.CrossEntropyLoss(ignore_index=morpho.PAD),
        metrics={"accuracy": torchmetrics.Accuracy("multiclass", num_classes=len(morpho.train.tags.string_vocab), ignore_index=morpho.PAD)},
        logdir=npfl138.format_logdir("logs/{file-}{timestamp}{-config}", **vars(args)),
    )

    logs = model.fit(train, dev=dev, epochs=args.epochs)

    # Generate test set annotations, but in `logdir` to allow parallel execution.
    os.makedirs(logdir, exist_ok=True)
    with open(os.path.join(logdir, "tagger_competition.txt"), "w", encoding="utf-8") as predictions_file:
        # Predict the tags on the test set. The following code assumes you use the same
        # output structure as in `tagger_we`, i.e., that for each sentence, the predictions are
        # a Numpy vector of shape `[num_tags, sentence_len_or_more]`, where `sentence_len_or_more`
        # is the length of the corresponding batch.
        predictions = model.predict(test, data_with_labels=True, as_numpy=True)

        for predicted_tags, words in zip(predictions, morpho.test.words.strings):
            for predicted_tag in predicted_tags[:, :len(words)].argmax(axis=0):
                print(morpho.train.tags.string_vocab.string(predicted_tag), file=predictions_file)
            print(file=predictions_file)


if __name__ == "__main__":
    main_args = parser.parse_args([] if "__file__" not in globals() else None)
    main(main_args)
