#!/usr/bin/env python3
import argparse

import torch
import torchmetrics

import npfl138
npfl138.require_version("2526.8")
from npfl138.datasets.morpho_dataset import MorphoDataset

parser = argparse.ArgumentParser()
# These arguments will be set appropriately by ReCodEx, even if you change them.
parser.add_argument("--batch_size", default=10, type=int, help="Batch size.")
parser.add_argument("--epochs", default=5, type=int, help="Number of epochs.")
parser.add_argument("--label_smoothing", default=0.0, type=float, help="Label smoothing.")
parser.add_argument("--max_sentences", default=None, type=int, help="Maximum number of sentences to load.")
parser.add_argument("--recodex", default=False, action="store_true", help="Evaluation in ReCodEx.")
parser.add_argument("--rnn", default="LSTM", choices=["LSTM", "GRU"], help="RNN layer type.")
parser.add_argument("--rnn_dim", default=64, type=int, help="RNN layer dimension.")
parser.add_argument("--seed", default=219, type=int, help="Random seed.")
parser.add_argument("--show_predictions", default=False, action="store_true", help="Show predicted tag sequences.")
parser.add_argument("--threads", default=1, type=int, help="Maximum number of threads to use.")
parser.add_argument("--we_dim", default=128, type=int, help="Word embedding dimension.")
# If you add more arguments, ReCodEx will keep them with your default values.


class Dataset(npfl138.TransformedDataset):
    def transform(self, example):
        # TODO(tagger_we): Construct a single example, each consisting of the following pair:
        # - a PyTorch tensor of integer ids of input words as input,
        # - a PyTorch tensor of integer tag ids as targets.
        # To create the ids, use `string_vocab` of `self.dataset.words` and `self.dataset.tags`.
        word_ids = torch.tensor(self.dataset.words.string_vocab.indices(example["words"]))
        tag_ids = torch.tensor(self.dataset.tags.string_vocab.indices(example["tags"]))
        return word_ids, tag_ids

    def collate(self, batch):
        # Construct a single batch, where `batch` is a list of examples
        # generated by `transform`.
        word_ids, tag_ids = zip(*batch)
        # TODO(tagger_we): Combine `word_ids` into a single tensor, padding shorter
        # sequences to length of the longest sequence in the batch with zeros
        # using `torch.nn.utils.rnn.pad_sequence` with `batch_first=True` argument.
        word_ids = torch.nn.utils.rnn.pad_sequence(word_ids, batch_first=True)
        # TODO(tagger_we): Process `tag_ids` analogously to `word_ids`.
        tag_ids = torch.nn.utils.rnn.pad_sequence(tag_ids, batch_first=True)
        return word_ids, tag_ids


class Model(npfl138.TrainableModule):
    def __init__(self, args: argparse.Namespace, train: MorphoDataset.Dataset) -> None:
        super().__init__()
        self._show_predictions = args.show_predictions
        # TODO: Compute the transition matrix `A` of shape `[num_tags, num_tags]`, so
        # that `A[i, j]` is 0/1 depending on whether the tag `j` is allowed to follow
        # the tag `i` (according to our BIO encoding; not necessarily in the data).
        # The tag strings can be obtained by calling `list(train.tags.string_vocab)`.
        tags = list(train.tags.string_vocab)
        num_tags = len(tags)
        self._o_tag = tags.index("O")
        A = torch.zeros([num_tags, num_tags])
        for i in range(num_tags):
            for j in range(num_tags):
                if tags[j].startswith("I-"):
                    A[i,j] = ((tags[i].startswith("B-") or tags[i].startswith("I-")) and tags[i][2:] == tags[j][2:])
                else:
                    A[i,j] = 1

        # The following call will create `self._A` and it will become part of the object state.
        self.register_buffer("_A", A)

        # Create all needed layers.
        # TODO(tagger_we): Create a `torch.nn.Embedding` layer, embedding the word ids
        # from `train.words.string_vocab` to dimensionality `args.we_dim`.
        self._word_embedding = torch.nn.Embedding(num_embeddings=len(train.words.string_vocab), embedding_dim=args.we_dim)

        # TODO(tagger_we): Create an RNN layer, either `torch.nn.LSTM` or `torch.nn.GRU` depending
        # on `args.rnn`. The layer should be bidirectional (`bidirectional=True`) with
        # dimensionality `args.rnn_dim`. During the model computation, the layer will
        # process the word embeddings generated by the `self._word_embedding` layer,
        # and we will sum the outputs of forward and backward directions.
        if args.rnn == "LSTM": 
            self._word_rnn = torch.nn.LSTM(input_size=args.we_dim, hidden_size=args.rnn_dim, bidirectional=True)
        else: 
            self._word_rnn = torch.nn.GRU(input_size=args.we_dim, hidden_size=args.rnn_dim, bidirectional=True)

        # TODO(tagger_we): Create an output linear layer (`torch.nn.Linear`) processing the RNN output,
        # producing logits for tag prediction; `train.tags.string_vocab` is the tag vocabulary.
        self._output_layer = torch.nn.Linear(in_features=args.rnn_dim, out_features=num_tags)

    def forward(self, word_ids: torch.Tensor) -> torch.Tensor:
        # TODO(tagger_we): Start by embedding the `word_ids` using the word embedding layer.
        hidden = self._word_embedding(word_ids)

        # TODO(tagger_we): Process the embedded words through the RNN layer. Because the sentences
        # have different length, you have to use `torch.nn.utils.rnn.pack_padded_sequence`
        # to construct a variable-length `PackedSequence` from the input. You need to compute
        # the length of each sentence in the batch (by counting non-`MorphoDataset.PAD` tokens);
        # note that these lengths must be on CPU, so you might need to use the `.cpu()` method.
        # Finally, also pass `batch_first=True` and `enforce_sorted=False` to the call.
        lengths = (word_ids != MorphoDataset.PAD).sum(dim=1).cpu()
        packed = torch.nn.utils.rnn.pack_padded_sequence(input=hidden, lengths=lengths, batch_first=True, enforce_sorted=False)

        # TODO(tagger_we): Pass the `PackedSequence` through the RNN, choosing the appropriate output.
        packed, _ = self._word_rnn(packed)

        # TODO(tagger_we): Unpack the RNN output using the `torch.nn.utils.rnn.pad_packed_sequence` with
        # `batch_first=True` argument. Then sum the outputs of forward and backward directions.
        hidden, _ = torch.nn.utils.rnn.pad_packed_sequence(packed, batch_first=True)
        hidden = (hidden[:, :, :self._word_rnn.hidden_size] + hidden[:, :, self._word_rnn.hidden_size:])

        # TODO(tagger_we): Pass the RNN output through the output layer. Such an output has a shape
        # `[batch_size, sequence_length, num_tags]`, but the loss and the metric expect
        # the `num_tags` dimension to be in front (`[batch_size, num_tags, sequence_length]`),
        # so you need to reorder the dimensions.
        hidden = self._output_layer(hidden)

        return hidden.permute(0,2,1)

    def constrained_decoding_old(self, logits: torch.Tensor, word_ids: torch.Tensor) -> torch.Tensor:
        B, N = word_ids.shape
        _, num_tags, _ = logits.shape
        A = self._A
        o_tag = self._o_tag

        alpha = torch.full([B, N, num_tags],-float("inf"))
        beta = torch.zeros([B, N, num_tags])

        lengths = (word_ids != MorphoDataset.PAD).sum(dim=1)
        for b in range(B):
            length = lengths[b].item()
            for k in range(num_tags):
                if A[o_tag, k] == 1:
                    alpha[b, 0, k] = logits[b, k, 0]
            for t in range(1, length):
                for k in range(num_tags):
                    best_val = -float("inf")
                    best_idx = 0
                    for j in range(num_tags):
                        if A[j, k] == 1 and alpha[b, t-1, j] > best_val:
                            best_val = alpha[b, t-1, j]
                            best_idx = j
                    alpha[b, t, k] = logits[b, k, t] + best_val
                    beta[b, t, k] = best_idx

        most_probable = torch.full([B, N], MorphoDataset.PAD)
        for b in range(B):
            length = lengths[b].item()
            most_probable[b, length-1] = alpha[b, length-1].argmax()
            # Follow backpointers
            for t in range(length-1, 0, -1):
                current_tag = most_probable[b, t]
                most_probable[b, t-1] = beta[b, t, current_tag]
        return most_probable


    def constrained_decoding(self, logits: torch.Tensor, word_ids: torch.Tensor) -> torch.Tensor:
        B, N = word_ids.shape
        _, num_tags, _ = logits.shape
        A = self._A
        o_tag = self._o_tag
        device = logits.device

        neg_inf = -float("inf")
        # Additive transition scores: 0 where (from -> to) is allowed, -inf otherwise.
        log_A = torch.where(A == 1, torch.zeros_like(A), torch.full_like(A, neg_inf))  # [from, to]

        lengths = (word_ids != MorphoDataset.PAD).sum(dim=1)

        alpha = torch.full([B, N, num_tags], neg_inf, device=device)
        beta = torch.zeros([B, N, num_tags], dtype=torch.long, device=device)

        # t = 0: transition from the virtual "O" tag preceding the sequence.
        init_mask = (A[o_tag] == 1)  # [num_tags]
        alpha[:, 0, :] = torch.where(init_mask, logits[:, :, 0], torch.full_like(logits[:, :, 0], neg_inf))

        for t in range(1, N):
            # candidate[b, j, k] = alpha[b, t-1, j] + log_A[j, k]  -- score of transitioning j -> k
            candidate = alpha[:, t - 1, :].unsqueeze(2) + log_A.unsqueeze(0)  # [B, from, to]
            best_val, best_idx = candidate.max(dim=1)                        # both [B, to]
            alpha[:, t, :] = logits[:, :, t] + best_val
            beta[:, t, :] = best_idx

        most_probable = torch.full([B, N], MorphoDataset.PAD, dtype=torch.long, device=device)
        for b in range(B):
            length = lengths[b].item()
            most_probable[b, length - 1] = alpha[b, length - 1].argmax()
            for t in range(length - 1, 0, -1):
                current_tag = most_probable[b, t]
                most_probable[b, t - 1] = beta[b, t, current_tag]

        return most_probable
        

    def compute_metrics(self, y_pred, y, word_ids):
        self.metrics["accuracy"].update(y_pred, y)
        if self.training:
            return {"accuracy": self.metrics["accuracy"]}

        # Perform greedy decoding.
        predictions_greedy = y_pred.argmax(dim=1)
        predictions_greedy.masked_fill_(word_ids == MorphoDataset.PAD, MorphoDataset.PAD)
        self.metrics["f1_greedy"].update(predictions_greedy, y)

        # TODO: Perform constrained decoding by calling `self.constrained_decoding`
        # on `y_pred` and `word_ids`.
        predictions = self.constrained_decoding(y_pred, word_ids)
        self.metrics["f1_constrained"].update(predictions, y)

        if self._show_predictions:
            for tags in predictions:
                print(*[self.metrics["f1_constrained"]._labels[tag] for tag in tags])

        return self.metrics

    def predict_step(self, xs):
        with torch.no_grad():
            # Perform constrained decoding and trim the padding tags from the predictions.
            for item in self.constrained_decoding(self.forward(*xs), *xs):
                yield item[item != MorphoDataset.PAD]


def main(args: argparse.Namespace) -> dict[str, float]:
    # Set the random seed and the number of threads.
    npfl138.startup(args.seed, args.threads)
    npfl138.global_keras_initializers()

    # Load the data.
    morpho = MorphoDataset("czech_cnec", max_sentences=args.max_sentences)

    # Prepare the data for training.
    train = Dataset(morpho.train).dataloader(batch_size=args.batch_size, shuffle=True)
    dev = Dataset(morpho.dev).dataloader(batch_size=args.batch_size)

    # Create the model and train.
    model = Model(args, morpho.train)

    model.configure(
        # TODO(tagger_we): Create the Adam optimizer.
        optimizer=torch.optim.Adam(model.parameters()),
        # TODO: Use `torch.nn.CrossEntropyLoss` to instantiate the loss function.
        # Pass `ignore_index=morpho.PAD` to the constructor to ignore padding tags
        # during loss computation; also pass `label_smoothing=args.label_smoothing`.
        loss=torch.nn.CrossEntropyLoss(ignore_index=morpho.PAD, label_smoothing=args.label_smoothing),
        metrics={
            # TODO(tagger_we): Create a `torchmetrics.Accuracy` metric, passing "multiclass" as
            # the first argument, `num_classes` set to the number of unique tags, and
            # again `ignore_index=morpho.PAD` to ignore the padded tags.
            "accuracy": torchmetrics.Accuracy("multiclass", num_classes=len(morpho.train.tags.string_vocab), ignore_index=morpho.PAD),
            # TODO: Create a `npfl138.metrics.BIOEncodingF1Score` for constrained decoding and also
            # for greedy decoding, passing both a `list(morpho.train.tags.string_vocab)`
            # and `ignore_index=morpho.PAD`.
            "f1_constrained": npfl138.metrics.BIOEncodingF1Score(list(morpho.train.tags.string_vocab), ignore_index=morpho.PAD),
            "f1_greedy": npfl138.metrics.BIOEncodingF1Score(list(morpho.train.tags.string_vocab), ignore_index=morpho.PAD),
        },
        logdir=npfl138.format_logdir("logs/{file-}{timestamp}{-config}", **vars(args)),
    )

    logs = model.fit(train, dev=dev, epochs=args.epochs)

    # Return development metrics for ReCodEx to validate.
    return {metric: value for metric, value in logs.items() if metric.startswith("dev:")}


if __name__ == "__main__":
    main_args = parser.parse_args([] if "__file__" not in globals() else None)
    main(main_args)
